import { createClient } from "@supabase/supabase-js";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(__dirname, "../.env.local") });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const locations = [
  // ── HISTORICAL ──────────────────────────────────────────────────────────────
  { name: "Sigiriya Rock Fortress", category: "Historical", lat: 7.9570, lng: 80.7603, description: "Ancient rock fortress and palace ruin rising 180m above the surrounding jungle. A UNESCO World Heritage Site featuring frescoes, mirror wall, and stunning panoramic views.", entry_fee: "LKR 4500 (foreign adults)", hours: "7:00am – 5:30pm daily" },
  { name: "Polonnaruwa Ancient City", category: "Historical", lat: 7.9403, lng: 81.0188, description: "UNESCO-listed medieval capital of Sri Lanka with well-preserved ruins including the Gal Vihara rock temple, Royal Palace, and Vatadage.", entry_fee: "LKR 3500 (foreign adults)", hours: "7:00am – 6:00pm daily" },
  { name: "Anuradhapura Sacred City", category: "Historical", lat: 8.3114, lng: 80.4037, description: "One of the ancient capitals of Sri Lanka, home to sacred Buddhist monuments, giant dagobas, and the Sri Maha Bodhi fig tree grown from the original Bodhi tree.", entry_fee: "LKR 3500 (foreign adults)", hours: "Open daily" },
  { name: "Galle Fort", category: "Historical", lat: 6.0269, lng: 80.2167, description: "A UNESCO World Heritage Dutch colonial fort built in the 16th century featuring cobblestone streets, colourful boutiques, cafes, and panoramic ocean views.", entry_fee: "Free", hours: "Open 24 hours" },
  { name: "Yapahuwa Rock Fortress", category: "Historical", lat: 7.8104, lng: 80.3347, description: "Dramatic 13th-century rock fortress built on a 100m granite outcrop, once capital of Sri Lanka and home to the Sacred Tooth Relic.", entry_fee: "LKR 500", hours: "8:00am – 5:00pm daily" },
  { name: "Ritigala Ancient Monastery", category: "Historical", lat: 8.1254, lng: 80.6907, description: "Mysterious ruined forest monastery hidden in the Ritigala Strict Nature Reserve with unusual double-platform meditation walkways.", entry_fee: "LKR 500", hours: "8:00am – 5:00pm daily" },
  { name: "Mihintale", category: "Historical", lat: 8.3497, lng: 80.5094, description: "Sacred hill considered the cradle of Buddhism in Sri Lanka where Mahinda preached to King Devanampiya Tissa. Climb 1,843 steps to the summit stupa.", entry_fee: "Free", hours: "Open daily" },
  { name: "Buduruwagala Rock Carvings", category: "Historical", lat: 6.3208, lng: 81.0069, description: "Seven rock-carved figures dating to the 9th century Mahayana Buddhist period, the tallest standing Buddha in Sri Lanka at 15m.", entry_fee: "LKR 200", hours: "6:00am – 6:00pm daily" },
  { name: "Medirigiriya Vatadage", category: "Historical", lat: 8.0024, lng: 80.9724, description: "An 8th-century circular relic house with three concentric rings of stone pillars surrounding a central dagoba, considered the finest vatadage in Sri Lanka.", entry_fee: "LKR 300", hours: "Open daily" },
  { name: "Nalanda Gedige", category: "Historical", lat: 7.7167, lng: 80.6833, description: "A unique 8th-century temple blending Mahayana Buddhist and Hindu architectural styles, now relocated to an island in the Nalanda tank.", entry_fee: "LKR 300", hours: "8:00am – 5:00pm daily" },
  { name: "Panduwasnuwara", category: "Historical", lat: 7.5681, lng: 80.2061, description: "Ruins of a 12th-century royal palace complex with a unique circular palace structure, one of the oldest in Sri Lanka.", entry_fee: "LKR 200", hours: "8:00am – 5:00pm daily" },
  { name: "Ridi Viharaya", category: "Historical", lat: 7.6578, lng: 80.4522, description: "Ancient cave temple in Kurunegala where silver ore was first discovered to fund Dutugamunu's campaigns. Features beautiful Kandyan murals.", entry_fee: "Free (donation)", hours: "Open daily" },
  { name: "Nuwara Wewa", category: "Historical", lat: 8.3600, lng: 80.4000, description: "One of the great irrigation tanks of Anuradhapura built by King Mahasena in the 3rd century, covering over 1,200 hectares.", entry_fee: "Free", hours: "Open daily" },
  { name: "Abhayagiri Dagoba", category: "Historical", lat: 8.3561, lng: 80.3947, description: "One of the world's largest ancient monuments, this massive dagoba in Anuradhapura reaches 75m and dates to the 1st century BC.", entry_fee: "Included in Anuradhapura ticket", hours: "Open daily" },
  { name: "Jetavanaramaya Dagoba", category: "Historical", lat: 8.3483, lng: 80.3975, description: "Once the world's third-tallest structure, this 3rd-century dagoba in Anuradhapura stands 71m tall and used more bricks than the Egyptian pyramid of Cheops.", entry_fee: "Included in Anuradhapura ticket", hours: "Open daily" },
  { name: "Yatagala Raja Maha Vihara", category: "Historical", lat: 6.1550, lng: 80.3858, description: "Cave temple near Unawatuna with ancient rock paintings and a reclining Buddha, surrounded by jungle-covered hills.", entry_fee: "Free (donation)", hours: "Open daily" },
  { name: "Mulkirigala Rock Temple", category: "Historical", lat: 6.1122, lng: 80.5453, description: "Series of cave temples perched 200m above the plain with ancient frescoes and views across the southern plains.", entry_fee: "LKR 300", hours: "8:00am – 5:00pm daily" },
  { name: "Weerawila Wewa Bird Sanctuary", category: "Historical", lat: 6.2722, lng: 81.1697, description: "Ancient irrigation tank surrounded by dry-zone forest, important wintering ground for migratory birds and home to painted storks and pelicans.", entry_fee: "Free", hours: "Open daily" },
  { name: "Kantarodai", category: "Historical", lat: 9.7728, lng: 80.0472, description: "Archaeological site in Jaffna featuring dozens of miniature stupas believed to be reliquaries from the 2nd to 11th centuries.", entry_fee: "Free", hours: "Open daily" },
  { name: "Nainativu Island Temple", category: "Historical", lat: 9.6472, lng: 79.9569, description: "Sacred island in the Jaffna lagoon home to the Nagapooshani Amman Temple, accessible only by boat, an important Hindu pilgrimage site.", entry_fee: "Free", hours: "Open daily" },

  // ── TEMPLE ──────────────────────────────────────────────────────────────────
  { name: "Temple of the Tooth (Sri Dalada Maligawa)", category: "Temple", lat: 7.2936, lng: 80.6413, description: "The most sacred Buddhist shrine in Sri Lanka, housing the relic of the tooth of the Buddha inside the royal palace complex in Kandy. A UNESCO World Heritage Site.", entry_fee: "LKR 1500 (foreign adults)", hours: "6:30am – 8:00pm daily" },
  { name: "Dambulla Cave Temple", category: "Temple", lat: 7.8567, lng: 80.6488, description: "UNESCO-listed cave temple complex of five caves containing 153 Buddha statues and murals covering over 2,100 sq metres, dating to the 1st century BC.", entry_fee: "LKR 1500 (foreign adults)", hours: "7:30am – 5:30pm daily" },
  { name: "Kelaniya Raja Maha Vihara", category: "Temple", lat: 7.0031, lng: 79.9219, description: "One of the most sacred Buddhist temples in Sri Lanka, believed to have been visited by the Buddha himself. Famous for its 20th-century murals.", entry_fee: "Free (donation)", hours: "6:00am – 8:00pm daily" },
  { name: "Gangaramaya Temple", category: "Temple", lat: 6.9168, lng: 79.8578, description: "Eclectic Buddhist temple complex in Colombo featuring an eclectic mix of Sri Lankan, Thai, Indian, and Chinese architecture with an extensive museum.", entry_fee: "LKR 300", hours: "6:00am – 10:00pm daily" },
  { name: "Embekke Devale", category: "Temple", lat: 7.2500, lng: 80.5833, description: "14th-century shrine near Kandy renowned for its exquisite woodcarvings of dancers, wrestlers, and mythological figures.", entry_fee: "Free (donation)", hours: "Open daily" },
  { name: "Lankatilaka Vihara", category: "Temple", lat: 7.2594, lng: 80.5456, description: "A 14th-century image house built on a granite outcrop near Kandy, featuring a remarkable four-storey brick tower and Kandyan-period paintings.", entry_fee: "Free (donation)", hours: "Open daily" },
  { name: "Gadaladeniya Temple", category: "Temple", lat: 7.2444, lng: 80.5200, description: "14th-century temple near Kandy built in a South Indian style with a stone pavilion and a Buddha statue made from a single stone.", entry_fee: "Free (donation)", hours: "Open daily" },
  { name: "Natha Devale", category: "Temple", lat: 7.2929, lng: 80.6378, description: "The oldest surviving monument in Kandy dating to the 14th century, dedicated to the Bodhisattva Natha (Maitreya).", entry_fee: "Free", hours: "Open daily" },
  { name: "Koneswaram Temple", category: "Temple", lat: 8.5778, lng: 81.2344, description: "Ancient Hindu temple on a cliff headland in Trincomalee dedicated to Lord Shiva with commanding views over the natural harbour.", entry_fee: "LKR 200", hours: "6:00am – 6:00pm daily" },
  { name: "Munneswaram Temple", category: "Temple", lat: 7.7622, lng: 79.9006, description: "Ancient regional Hindu temple complex dating to before the 10th century, an important pilgrimage site for both Hindus and Buddhists.", entry_fee: "Free", hours: "6:00am – 8:00pm daily" },
  { name: "Kathiresan Kovil", category: "Temple", lat: 6.9345, lng: 79.8600, description: "Colourful Hindu temple in Colombo's Pettah district dedicated to Lord Murugan, the site of the colourful Vel festival procession.", entry_fee: "Free", hours: "5:00am – 12:00pm, 4:00pm – 9:00pm" },
  { name: "Nagadeepa Temple", category: "Temple", lat: 9.7122, lng: 79.8919, description: "Sacred Buddhist island temple in the Jaffna lagoon said to have been visited by the Buddha during his second visit to Sri Lanka.", entry_fee: "Free", hours: "Open daily" },
  { name: "Seruwawila Stupa", category: "Temple", lat: 8.3208, lng: 81.3514, description: "Ancient stupa in Trincomalee district housing a sacred frontal bone relic of the Buddha, major pilgrimage site in the east.", entry_fee: "Free", hours: "Open daily" },
  { name: "Weligama Kustaraja Rock Statue", category: "Temple", lat: 5.9742, lng: 80.4353, description: "Impressive 3m carved rock statue near Weligama believed to depict a 9th-century Mahayana Buddhist figure, visible from the main road.", entry_fee: "Free", hours: "Open daily" },
  { name: "Ibbankatuwa Megalithic Tombs", category: "Historical", lat: 7.8739, lng: 80.5353, description: "Prehistoric burial site near Dambulla featuring large stone slabs covering burial chambers dating to around 600 BC.", entry_fee: "LKR 200", hours: "8:00am – 5:00pm daily" },

  // ── BEACH ────────────────────────────────────────────────────────────────────
  { name: "Mirissa Beach", category: "Beach", lat: 5.9448, lng: 80.4705, description: "Crescent-shaped beach in the south famous for whale watching, surfing, and laid-back beach bars with coconut tree-lined shores.", entry_fee: "Free", hours: "Open 24 hours" },
  { name: "Unawatuna Beach", category: "Beach", lat: 6.0106, lng: 80.2494, description: "Popular crescent beach sheltered by a rocky headland near Galle, ideal for swimming and snorkelling. Lined with restaurants and guesthouses.", entry_fee: "Free", hours: "Open 24 hours" },
  { name: "Hikkaduwa Beach", category: "Beach", lat: 6.1395, lng: 80.1032, description: "Lively beach town with a National Marine Sanctuary, famous for coral reefs, sea turtles, surfing, and a buzzing nightlife strip.", entry_fee: "Free", hours: "Open 24 hours" },
  { name: "Arugam Bay", category: "Beach", lat: 6.8400, lng: 81.8376, description: "World-class surf beach on the east coast, rated one of the top 10 surfing spots in the world. Best from May to October.", entry_fee: "Free", hours: "Open 24 hours" },
  { name: "Nilaveli Beach", category: "Beach", lat: 8.7147, lng: 81.2169, description: "Pristine white sand beach near Trincomalee on the east coast, one of Sri Lanka's most beautiful and unspoilt stretches of coast.", entry_fee: "Free", hours: "Open 24 hours" },
  { name: "Pasikuda Beach", category: "Beach", lat: 7.9378, lng: 81.5606, description: "Calm, shallow turquoise lagoon-style beach on the east coast, ideal for swimming and snorkelling with some of Sri Lanka's clearest water.", entry_fee: "Free", hours: "Open 24 hours" },
  { name: "Bentota Beach", category: "Beach", lat: 6.4221, lng: 79.9978, description: "Long stretch of golden sand beach with the Bentota River estuary creating a calm lagoon perfect for water sports including jet skiing and windsurfing.", entry_fee: "Free", hours: "Open 24 hours" },
  { name: "Tangalle Beach", category: "Beach", lat: 6.0234, lng: 80.7938, description: "Beautiful wild beach area in the deep south with multiple bays separated by rocky headlands, a nesting site for olive ridley turtles.", entry_fee: "Free", hours: "Open 24 hours" },
  { name: "Negombo Beach", category: "Beach", lat: 7.2100, lng: 79.8343, description: "Long beach north of Colombo popular with tourists due to its proximity to the airport, known for fresh seafood and a lively fish market.", entry_fee: "Free", hours: "Open 24 hours" },
  { name: "Weligama Beach", category: "Beach", lat: 5.9742, lng: 80.4295, description: "Sheltered bay beach popular for beginner surfing lessons with gentle waves. Known for stilt fishing and panoramic seafront sunsets.", entry_fee: "Free", hours: "Open 24 hours" },
  { name: "Kalkudah Beach", category: "Beach", lat: 7.9614, lng: 81.5519, description: "Remote, pristine white sand beach on the east coast near Pasikuda with calm turquoise waters, largely undeveloped and tranquil.", entry_fee: "Free", hours: "Open 24 hours" },
  { name: "Uppuveli Beach", category: "Beach", lat: 8.6258, lng: 81.2089, description: "Quiet beach just north of Trincomalee, ideal for swimming and snorkelling with clear water and a relaxed village atmosphere.", entry_fee: "Free", hours: "Open 24 hours" },
  { name: "Polhena Beach", category: "Beach", lat: 5.9453, lng: 80.5367, description: "Rocky reef beach near Matara ideal for snorkelling with sea turtles in the protected cove. Popular with locals and adventurous tourists.", entry_fee: "Free", hours: "Open daily" },
  { name: "Induruwa Beach", category: "Beach", lat: 6.3614, lng: 80.0206, description: "Quiet beach between Bentota and Hikkaduwa with calm waters, a turtle hatchery, and a relaxed atmosphere away from crowds.", entry_fee: "Free", hours: "Open 24 hours" },
  { name: "Koggala Beach", category: "Beach", lat: 5.9956, lng: 80.3300, description: "Long undeveloped beach near Galle with a historical wartime airstrip and the Koggala Lake nearby with cinnamon island.", entry_fee: "Free", hours: "Open 24 hours" },

  // ── WILDLIFE ──────────────────────────────────────────────────────────────────
  { name: "Yala National Park", category: "Wildlife", lat: 6.3728, lng: 81.5197, description: "Sri Lanka's most visited national park with the world's highest leopard density. Also home to elephants, sloth bears, mugger crocodiles, and 200+ bird species.", entry_fee: "LKR 3500 (entry) + vehicle fees", hours: "6:00am – 6:00pm daily" },
  { name: "Minneriya National Park", category: "Wildlife", lat: 8.0333, lng: 80.9000, description: "Famous for 'The Gathering' — one of the largest elephant gatherings on earth from June to September when hundreds congregate at the Minneriya tank.", entry_fee: "LKR 3500 (foreign adults)", hours: "7:00am – 6:00pm daily" },
  { name: "Udawalawe National Park", category: "Wildlife", lat: 6.4392, lng: 80.8956, description: "Best park in Sri Lanka to see large herds of wild elephants in open grassland. Also home to water buffalo, crocodiles, and raptors.", entry_fee: "LKR 3500 (foreign adults)", hours: "6:00am – 6:00pm daily" },
  { name: "Wilpattu National Park", category: "Wildlife", lat: 8.4500, lng: 80.0167, description: "Sri Lanka's largest national park featuring natural lakes (villus) and dense jungle. Home to leopards, sloth bears, elephants, and deer.", entry_fee: "LKR 3500 (foreign adults)", hours: "6:00am – 6:00pm daily" },
  { name: "Bundala National Park", category: "Wildlife", lat: 6.2014, lng: 81.2119, description: "UNESCO Biosphere Reserve and Ramsar wetland famous for thousands of migratory flamingos and shorebirds. Also home to elephants and crocodiles.", entry_fee: "LKR 1500 (foreign adults)", hours: "6:00am – 6:00pm daily" },
  { name: "Pinnawala Elephant Orphanage", category: "Wildlife", lat: 7.3011, lng: 80.3850, description: "World's largest elephant orphanage housing over 80 elephants. Watch the daily river bathing ritual and baby elephant feeding.", entry_fee: "LKR 3000 (foreign adults)", hours: "8:30am – 5:30pm daily" },
  { name: "Kumana National Park", category: "Wildlife", lat: 6.5833, lng: 81.7000, description: "Remote national park on the east coast famous for its Kumana Villu bird sanctuary, nesting ground for herons, pelicans, and painted storks.", entry_fee: "LKR 1500 (foreign adults)", hours: "6:00am – 6:00pm daily" },
  { name: "Kaudulla National Park", category: "Wildlife", lat: 8.1561, lng: 80.9142, description: "Part of the elephant corridor with Minneriya and Girithale, best visited from September to December for large elephant herds at the Kaudulla tank.", entry_fee: "LKR 3500 (foreign adults)", hours: "7:00am – 6:00pm daily" },
  { name: "Horton Plains National Park", category: "Wildlife", lat: 6.8098, lng: 80.8082, description: "UNESCO-listed plateau at 2,100m with cloud forest, wildlife, and World's End cliff. Home to sambar deer, purple-faced langurs, and endemic birds.", entry_fee: "LKR 3900 (foreign adults)", hours: "6:00am – 6:00pm daily" },
  { name: "Wasgamuwa National Park", category: "Wildlife", lat: 7.7167, lng: 80.9167, description: "Vast wilderness along the Mahaweli River with significant elephant populations and a high density of leopards, relatively uncrowded.", entry_fee: "LKR 1500 (foreign adults)", hours: "6:00am – 6:00pm daily" },
  { name: "Gal Oya National Park", category: "Wildlife", lat: 7.0167, lng: 81.2333, description: "Remote park around the Senanayake Samudra reservoir, the only national park in Sri Lanka where you can take a boat safari to spot elephants swimming between islands.", entry_fee: "LKR 1500 (foreign adults)", hours: "6:00am – 6:00pm daily" },
  { name: "Sinharaja Forest Reserve", category: "Wildlife", lat: 6.4011, lng: 80.4961, description: "UNESCO World Heritage rainforest and biosphere reserve — Sri Lanka's last viable area of primary tropical rainforest, home to 50% of endemic species.", entry_fee: "LKR 760 (foreign adults)", hours: "7:00am – 5:00pm daily" },
  { name: "Kosgoda Turtle Hatchery", category: "Wildlife", lat: 6.2886, lng: 80.0175, description: "Sea turtle conservation project on the south coast protecting five species of sea turtle. Visit at night to watch nesting females or hatchling releases.", entry_fee: "LKR 500", hours: "8:00am – 6:00pm (night visits arranged)" },
  { name: "Madhu Road Bird Sanctuary", category: "Wildlife", lat: 8.9731, lng: 80.0767, description: "Important wetland sanctuary in the northwest, a critical stopover for migratory birds along the Central Asian Flyway.", entry_fee: "Free", hours: "Open daily" },

  // ── WATERFALL ──────────────────────────────────────────────────────────────
  { name: "Bambarakanda Falls", category: "Waterfall", lat: 6.7386, lng: 80.8878, description: "Sri Lanka's highest waterfall at 263m, plunging through lush tea estate country in the Badulla district. Best visited during or just after the rainy season.", entry_fee: "Free", hours: "Open daily" },
  { name: "Diyaluma Falls", category: "Waterfall", lat: 6.6644, lng: 81.0058, description: "Second highest waterfall in Sri Lanka at 220m with a series of natural rock pools halfway up the hillside perfect for swimming.", entry_fee: "Free", hours: "Open daily" },
  { name: "Ravana Falls", category: "Waterfall", lat: 6.8506, lng: 81.0525, description: "One of the widest falls in Sri Lanka, a popular roadside attraction near Ella cascading 25m down a broad rock face. Linked to the Ramayana legend.", entry_fee: "Free", hours: "Open daily" },
  { name: "Baker's Falls", category: "Waterfall", lat: 6.8028, lng: 80.8042, description: "Stunning 20m waterfall inside Horton Plains National Park, accessible via a 9km circular hiking trail through cloud forest.", entry_fee: "Included in park entry", hours: "6:00am – 6:00pm daily" },
  { name: "Laxapana Falls", category: "Waterfall", lat: 6.9167, lng: 80.4667, description: "One of Sri Lanka's highest single-drop waterfalls at 126m, plunging into the Maskeli Oya river. Good viewpoint from the main road.", entry_fee: "Free", hours: "Open daily" },
  { name: "Aberdeen Falls", category: "Waterfall", lat: 6.9444, lng: 80.5889, description: "Dramatic 98m waterfall accessible by a short jungle hike near Nuwara Eliya, surrounded by tea plantations and tropical forest.", entry_fee: "Free", hours: "Open daily" },
  { name: "St. Clair's Falls", category: "Waterfall", lat: 6.9150, lng: 80.6303, description: "Known as 'Little Niagara of Sri Lanka', a wide two-tier waterfall visible from the main Colombo-Kandy road in the heart of tea country.", entry_fee: "Free", hours: "Open daily" },
  { name: "Devon Falls", category: "Waterfall", lat: 6.9197, lng: 80.6336, description: "97m waterfall near Nuwara Eliya cascading through tea plantations. Often viewed alongside St. Clair's Falls just down the road.", entry_fee: "Free", hours: "Open daily" },
  { name: "Bopath Falls", category: "Waterfall", lat: 6.7736, lng: 80.3639, description: "Distinctive 30m waterfall in Ratnapura district shaped like a bo leaf, set in a gorge surrounded by tropical vegetation.", entry_fee: "LKR 100", hours: "Open daily" },
  { name: "Dunhinda Falls", category: "Waterfall", lat: 7.0028, lng: 81.0375, description: "One of Sri Lanka's most beautiful waterfalls at 64m near Badulla, surrounded by forest with a misty spray cloud (dunhinda means 'smoky water').", entry_fee: "LKR 200", hours: "Open daily" },
  { name: "Ramboda Falls", category: "Waterfall", lat: 7.0033, lng: 80.6769, description: "109m waterfall visible from the Kandy-Nuwara Eliya highway, one of the most photographed roadside waterfalls in the hill country.", entry_fee: "Free", hours: "Open daily" },
  { name: "Kirindi Falls", category: "Waterfall", lat: 6.9861, lng: 80.7575, description: "Scenic waterfall and deep pool near Nuwara Eliya accessible by a short hike, less crowded than the main tourist falls.", entry_fee: "Free", hours: "Open daily" },

  // ── HIKING ────────────────────────────────────────────────────────────────
  { name: "Adam's Peak (Sri Pada)", category: "Hiking", lat: 6.8096, lng: 80.4994, description: "Sacred 2,243m mountain with a footprint-shaped hollow at the summit, revered by Buddhists, Hindus, Muslims, and Christians alike. 5,500 steps to the top. Best season: December–May.", entry_fee: "Free", hours: "Season: Dec–May; trail open 2:00am onwards" },
  { name: "Ella Rock", category: "Hiking", lat: 6.8756, lng: 81.0650, description: "Rewarding 3-hour hike from Ella through tea estates and jungle to the 1,041m summit with sweeping views of the surrounding valleys.", entry_fee: "Free", hours: "Recommended 6:00am start" },
  { name: "Little Adam's Peak", category: "Hiking", lat: 6.8817, lng: 81.0575, description: "Easy 2-hour hike from Ella with panoramic views. Perfect for sunrise. The trail passes through tea plantations and takes about 45 minutes each way.", entry_fee: "LKR 100 (tea estate fee)", hours: "5:30am – 6:00pm daily" },
  { name: "Pidurutalagala (Mount Pedro)", category: "Hiking", lat: 6.9594, lng: 80.7731, description: "Sri Lanka's highest peak at 2,524m near Nuwara Eliya. Access is restricted to some areas due to military installations but lower trails are accessible.", entry_fee: "Free (lower trails)", hours: "Daytime hours" },
  { name: "Knuckles Mountain Range", category: "Hiking", lat: 7.4167, lng: 80.7833, description: "UNESCO-listed biodiversity hotspot with misty peaks up to 1,906m, pristine streams, waterfalls, and endemic wildlife. Multiple multi-day trails.", entry_fee: "LKR 700 (foreign adults)", hours: "Open daily" },
  { name: "Mihintale Hill", category: "Hiking", lat: 8.3497, lng: 80.5094, description: "1,843 stone steps lead to the summit stupa with panoramic views across the ancient city of Anuradhapura. Easier than it looks, reward is excellent.", entry_fee: "Free", hours: "Open daily" },
  { name: "Hanthana Mountain Range", category: "Hiking", lat: 7.2583, lng: 80.6083, description: "Series of peaks surrounding Kandy ideal for day hikes through tea estates with views back over the city and Kandy Lake.", entry_fee: "Free", hours: "Open daily" },
  { name: "World's End Hike", category: "Hiking", lat: 6.8028, lng: 80.8042, description: "4.5km trail inside Horton Plains to a dramatic 880m sheer cliff with views across the southern plains. Best before 9am before mist rolls in.", entry_fee: "Included in park entry (LKR 3900)", hours: "6:00am – 8:00am (best for clear views)" },
  { name: "Riverston Peak", category: "Hiking", lat: 7.4819, lng: 80.7736, description: "Scenic drive and hike to the edge of the Knuckles Range with a dramatic escarpment and sweeping views. Mini-World's End of Knuckles.", entry_fee: "Free", hours: "Open daily" },
  { name: "Lakegala Rock", category: "Hiking", lat: 7.4794, lng: 80.7875, description: "Dramatic 1,340m granite outcrop in the Knuckles Range, a challenging scramble requiring a rope for the summit section. Outstanding panoramic views.", entry_fee: "Free (guide recommended)", hours: "Best started before 7:00am" },

  // ── VIEWPOINT ─────────────────────────────────────────────────────────────
  { name: "Nine Arches Bridge, Ella", category: "Viewpoint", lat: 6.8797, lng: 81.0542, description: "Sri Lanka's most iconic colonial-era railway viaduct, built entirely in stone without steel between 1919–21. Best viewed from above with a train passing.", entry_fee: "Free", hours: "Open 24 hours (trains 6am–8pm)" },
  { name: "Lipton's Seat", category: "Viewpoint", lat: 6.7581, lng: 81.0100, description: "Panoramic viewpoint at 1,970m where Sir Thomas Lipton surveyed his tea empire. On a clear day you can see the southern coastline 50km away.", entry_fee: "Free (tea estate fee may apply)", hours: "5:30am – 5:30pm daily" },
  { name: "Ambuluwawa Tower", category: "Viewpoint", lat: 7.2172, lng: 80.5736, description: "Unique spiral tower rising from a biodiversity complex in the central highlands with 360-degree views. Nearby lake and forest trails.", entry_fee: "LKR 300", hours: "8:00am – 5:00pm daily" },
  { name: "Ella Gap Viewpoint", category: "Viewpoint", lat: 6.8750, lng: 81.0450, description: "Stunning natural gap in the mountain ridge visible from Ella town, framing a view all the way down to the southern coastal plains.", entry_fee: "Free", hours: "Open 24 hours" },
  { name: "Bible Rock (Bathalegala)", category: "Viewpoint", lat: 7.0208, lng: 80.4736, description: "Twin flat-topped rock peaks visible from the Colombo-Kandy highway, a challenging hike rewarded with stunning views of the surrounding countryside.", entry_fee: "Free", hours: "Open daily" },
  { name: "Yahangala Rock", category: "Viewpoint", lat: 7.0506, lng: 80.5889, description: "Large flat-topped granite rock near Kandy accessible by a moderate hike, popular with rock climbers and offering 360-degree panoramic views.", entry_fee: "Free", hours: "Open daily" },
  { name: "Lovers' Leap Viewpoint", category: "Viewpoint", lat: 6.9817, lng: 80.5647, description: "Dramatic cliff viewpoint in the tea estate near Nuwara Eliya overlooking the Labukele tea estate valley with mist-covered hills.", entry_fee: "Free", hours: "Open daily" },
  { name: "Pussellawa Viewpoint", category: "Viewpoint", lat: 7.1167, lng: 80.7333, description: "Roadside viewpoint on the Kandy-Nuwara Eliya road with sweeping views across the Pussellawa valley and surrounding tea-covered hills.", entry_fee: "Free", hours: "Open daily" },

  // ── MUSEUM ────────────────────────────────────────────────────────────────
  { name: "National Museum of Colombo", category: "Museum", lat: 6.9105, lng: 79.8617, description: "Sri Lanka's largest museum housing an exceptional collection of antiques from the Kandyan Kingdom, including the throne and crown of the last king.", entry_fee: "LKR 500 (foreign adults)", hours: "9:00am – 5:00pm (closed Fridays)" },
  { name: "Colombo Dutch Museum", category: "Museum", lat: 6.9350, lng: 79.8545, description: "Former Dutch Governor's residence from 1752 housing artefacts from the Dutch colonial era including furniture, coins, maps, and pottery.", entry_fee: "LKR 200", hours: "9:00am – 5:00pm (closed Fridays)" },
  { name: "Kandy National Museum", category: "Museum", lat: 7.2939, lng: 80.6406, description: "Museum within the Kandy palace complex displaying royal regalia, Kandyan jewellery, ivory carvings, and traditional costumes.", entry_fee: "LKR 300", hours: "9:00am – 5:00pm (closed Fridays)" },
  { name: "Ratnapura Gem Museum", category: "Museum", lat: 6.6804, lng: 80.3997, description: "Exhibits the gem-mining heritage of the gem capital of Sri Lanka with displays of sapphires, rubies, alexandrite, and the mining process.", entry_fee: "LKR 200", hours: "9:00am – 5:00pm daily" },
  { name: "Martin Wickramasinghe Museum", category: "Museum", lat: 5.9775, lng: 80.3606, description: "Folk museum in the birthplace of Sri Lanka's most celebrated author, showcasing traditional rural life, tools, and customs of coastal Sri Lanka.", entry_fee: "LKR 200", hours: "9:00am – 5:00pm (closed Tuesdays)" },
  { name: "Galle National Museum", category: "Museum", lat: 6.0269, lng: 80.2167, description: "Inside Galle Fort, this museum displays artefacts from the Dutch colonial period and ancient Sri Lankan history including maps and VOC items.", entry_fee: "LKR 200", hours: "9:00am – 5:00pm (closed Fridays)" },

  // ── GARDEN ────────────────────────────────────────────────────────────────
  { name: "Peradeniya Royal Botanical Garden", category: "Garden", lat: 7.2692, lng: 80.5975, description: "One of the finest botanical gardens in Asia, 147 acres along the Mahaweli River with an avenue of royal palms, giant Javan fig trees, and 4,000 plant species.", entry_fee: "LKR 1500 (foreign adults)", hours: "7:30am – 5:00pm daily" },
  { name: "Hakgala Botanical Garden", category: "Garden", lat: 6.9197, lng: 80.8014, description: "Montane botanical garden at 1,745m near Nuwara Eliya featuring a famous rose garden, Japanese garden, and Hakgala rock backdrop from Ramayana legend.", entry_fee: "LKR 1000 (foreign adults)", hours: "8:00am – 5:00pm daily" },
  { name: "Victoria Park, Nuwara Eliya", category: "Garden", lat: 6.9716, lng: 80.7694, description: "Beautiful public park in the heart of Nuwara Eliya with manicured gardens, ornamental flowers, and a large playing field. Best during the April season.", entry_fee: "LKR 100", hours: "7:00am – 7:00pm daily" },
  { name: "Heritance Tea Factory", category: "Garden", lat: 6.9511, lng: 80.7808, description: "A converted Victorian tea factory perched amid the finest tea gardens in Sri Lanka. Tea tours explain the process from leaf to cup with tastings.", entry_fee: "LKR 500 (tea tour)", hours: "8:00am – 6:00pm daily" },
  { name: "Kandy Lake", category: "Garden", lat: 7.2933, lng: 80.6433, description: "Artificial lake built by the last Kandyan king in 1807, surrounded by a scenic cloud walk. The island in the centre was once a royal bathing spot.", entry_fee: "Free", hours: "Open 24 hours" },

  // ── OTHER ─────────────────────────────────────────────────────────────────
  { name: "Independence Memorial Hall", category: "Other", lat: 6.9106, lng: 79.8618, description: "Monument built to commemorate Sri Lanka's independence from British rule in 1948, modelled on the Audience Hall of the Kandyan kings.", entry_fee: "Free", hours: "Open daily (exterior 24hrs)" },
  { name: "Colombo Lotus Tower", category: "Other", lat: 6.9271, lng: 79.8639, description: "South Asia's tallest tower at 350m with an observation deck, restaurants, and LED light displays. Resembles a lotus flower in bloom.", entry_fee: "LKR 1000 (observation deck)", hours: "9:00am – 10:00pm daily" },
  { name: "Dutch Hospital Colombo", category: "Other", lat: 6.9361, lng: 79.8454, description: "Beautifully restored 17th-century Dutch colonial hospital building now converted into a shopping and dining complex in the Colombo Fort area.", entry_fee: "Free", hours: "10:00am – 10:00pm daily" },
  { name: "Pettah Market", category: "Other", lat: 6.9406, lng: 79.8520, description: "Colombo's most vibrant and chaotic wholesale market district with dedicated streets for textiles, electronics, spices, and everything in between.", entry_fee: "Free", hours: "Mon–Sat 8:00am – 6:00pm" },
  { name: "Nuwara Eliya Post Office", category: "Other", lat: 6.9697, lng: 80.7681, description: "Charming colonial-era pink post office dating to 1894, one of Nuwara Eliya's most photographed colonial buildings. Still a working post office.", entry_fee: "Free", hours: "Mon–Fri 8:00am – 4:00pm" },
  { name: "Trincomalee Harbour", category: "Other", lat: 8.5667, lng: 81.2333, description: "One of the world's finest natural deep-water harbours, historically strategic and offering whale and dolphin watching from April to September.", entry_fee: "Free", hours: "Open 24 hours" },
  { name: "Batticaloa Lagoon", category: "Other", lat: 7.7170, lng: 81.7008, description: "Famous lagoon said to produce musical sounds from the bottom ('singing fish'), best experienced by boat. Surrounded by Dutch fort ruins.", entry_fee: "Free (boat hire ~LKR 500)", hours: "Open daily" },
  { name: "Mannar Island", category: "Other", lat: 8.9781, lng: 79.9044, description: "Remote island connected by causeway, known for the ancient Baobab tree (claimed to be 700 years old), historic fort, and flamingo flocks.", entry_fee: "Free", hours: "Open 24 hours" },
  { name: "Dutch Fort Batticaloa", category: "Historical", lat: 7.7225, lng: 81.7008, description: "17th-century Dutch fort on the Batticaloa lagoon, one of the best-preserved Dutch forts in Sri Lanka with original star-shaped ramparts.", entry_fee: "Free", hours: "Open daily" },
  { name: "Jaffna Fort", category: "Historical", lat: 9.6603, lng: 80.0167, description: "Large Portuguese and Dutch fort on the Jaffna lagoon, one of the largest and most intact colonial fortifications in Sri Lanka.", entry_fee: "Free", hours: "Open daily" },
  { name: "Keerimalai Hot Springs", category: "Other", lat: 9.8339, lng: 80.0386, description: "Natural freshwater springs at the northernmost tip of Sri Lanka fed by underground seawater filtration, used for bathing and believed to have healing properties.", entry_fee: "Free", hours: "Open daily" },
  { name: "Ravana Cave", category: "Historical", lat: 6.8617, lng: 81.0456, description: "Cave system near Ella linked to the Ramayana legend, said to be where King Ravana hid Sita. Features stalactites and a sacred shrine inside.", entry_fee: "LKR 200", hours: "8:00am – 5:00pm daily" },
  { name: "Gregory Lake, Nuwara Eliya", category: "Other", lat: 6.9686, lng: 80.7758, description: "Scenic artificial lake in the heart of Nuwara Eliya where you can hire pedal boats, row boats, and horses. Surrounded by walking paths and manicured gardens.", entry_fee: "Free (boat hire ~LKR 500)", hours: "7:00am – 6:00pm daily" },
  { name: "Colombo Fort Clock Tower", category: "Historical", lat: 6.9353, lng: 79.8487, description: "Iconic 1857 lighthouse and clock tower at the heart of Colombo Fort, one of the city's oldest surviving colonial structures.", entry_fee: "Free (exterior)", hours: "Open 24 hours" },
  { name: "Whale Watch Mirissa", category: "Wildlife", lat: 5.9403, lng: 80.4736, description: "Year-round blue whale and sperm whale watching tours departing from Mirissa harbour. Best season November–April for blue whales.", entry_fee: "LKR 4500–6000 (boat tour)", hours: "Departs 6:30am daily (season dependent)" },
  { name: "Turtle Hatchery Kosgoda", category: "Wildlife", lat: 6.2886, lng: 80.0175, description: "Community sea turtle conservation project on the west coast protecting and hatching eggs from five species of sea turtle with evening releases.", entry_fee: "LKR 300", hours: "8:00am – 10:00pm" },
  { name: "Saptha Kanya Waterfall", category: "Waterfall", lat: 7.1311, lng: 80.5694, description: "A chain of seven small waterfalls in Kandy district cascading through forest, a pleasant picnic spot accessible by a short trail.", entry_fee: "Free", hours: "Open daily" },
  { name: "Mahiyanganaya", category: "Historical", lat: 7.3489, lng: 81.0019, description: "One of the most sacred Buddhist sites in Sri Lanka, believed to be where the Buddha made his first visit to the island and preached to the Yakkha tribe.", entry_fee: "Free (donation)", hours: "Open daily" },
  { name: "Nuwara Eliya Racecourse", category: "Other", lat: 6.9681, lng: 80.7736, description: "Sri Lanka's only horse racing venue, built by the British in 1875 surrounded by mountains. Races held during the April season. Scenic walk any time.", entry_fee: "LKR 200 (race days)", hours: "Open daily (races: April season)" },
  { name: "Aukana Buddha Statue", category: "Historical", lat: 8.0014, lng: 80.5714, description: "Magnificent 12m standing Buddha carved from a single granite rock in the 5th century, one of the finest examples of ancient Sri Lankan sculpture.", entry_fee: "LKR 300", hours: "7:00am – 5:30pm daily" },

  // ── MISSING LOCATIONS ────────────────────────────────────────────────────────
  { name: "Ruwanwelisaya", category: "Historical", lat: 8.3481, lng: 80.3969, description: "One of the world's greatest Buddhist monuments, this magnificent white dagoba in Anuradhapura was built by King Dutugamunu around 140 BC. Standing 55m tall with a perfect hemispherical dome, it is the most revered stupa in Sri Lanka and a major pilgrimage destination.", entry_fee: "Included in Anuradhapura ticket", hours: "Open daily" },
  { name: "Sri Maha Bodhi", category: "Temple", lat: 8.3457, lng: 80.3960, description: "The most sacred Buddhist tree in the world — a branch of the original Bodhi tree under which the Buddha attained enlightenment, transplanted to Anuradhapura by Princess Sangamitta in 249 BC. Claimed to be the oldest documented living tree in the world.", entry_fee: "Included in Anuradhapura ticket", hours: "Open daily" },
  { name: "Thuparama Dagoba", category: "Historical", lat: 8.3580, lng: 80.3952, description: "The oldest stupa in Sri Lanka, built by King Devanampiya Tissa in 307 BC to enshrine the right collar bone of the Buddha. The bell-shaped dagoba is surrounded by four concentric rings of beautiful stone pillars.", entry_fee: "Included in Anuradhapura ticket", hours: "Open daily" },
  { name: "Isurumuniya Vihara", category: "Temple", lat: 8.3330, lng: 80.3852, description: "Ancient rock temple in Anuradhapura carved into a large black granite outcrop, famous for the exquisite 'Isurumuniya Lovers' rock carving — considered one of the finest examples of ancient Sri Lankan art. Overlooks a scenic pond.", entry_fee: "LKR 200", hours: "8:00am – 5:00pm daily" },
  { name: "Pidurangala Rock", category: "Hiking", lat: 7.9600, lng: 80.7524, description: "A spectacular viewpoint offering the best panoramic view of Sigiriya Rock Fortress from across the jungle. The hike passes an ancient cave temple with a reclining Buddha before scrambling up bare rock to the summit — far less crowded than Sigiriya itself.", entry_fee: "LKR 500", hours: "6:00am – 5:30pm daily" },
  { name: "Kataragama", category: "Temple", lat: 6.4108, lng: 81.3342, description: "One of Sri Lanka's holiest and most visited pilgrimage sites, revered by Buddhists, Hindus, Muslims, and indigenous Veddah alike. The Maha Devalaya shrine complex is dedicated to God Kataragama (Skanda/Murugan), with three daily puja ceremonies accompanied by drumming and fire.", entry_fee: "Free", hours: "Puja at 4:30am, 10:30am & 6:30pm daily" },
  { name: "Matara Star Fort", category: "Historical", lat: 5.9475, lng: 80.5357, description: "A well-preserved Dutch star-shaped fortification built in 1763 in the heart of Matara, connected to the main Dutch ramparts by a bridge over the Nilwala River. Houses a small museum displaying Dutch colonial artefacts.", entry_fee: "LKR 200", hours: "8:00am – 5:00pm daily" },
  { name: "Viharamahadevi Park", category: "Garden", lat: 6.9108, lng: 79.8628, description: "Colombo's oldest and largest public park, originally named Victoria Park before being renamed after the ancient Sinhala queen. Features a golden seated Buddha statue, deer park, tropical flower beds, and century-old trees. A beloved green lung in the city centre.", entry_fee: "Free", hours: "6:00am – 6:00pm daily" },
  { name: "Brief Garden", category: "Garden", lat: 6.4378, lng: 80.0011, description: "A romantic 4-acre tropical garden near Beruwala created by landscape architect Bevis Bawa over six decades. Features outdoor sculptures by Donald Friend, frangipani terraces, lily ponds, and dense jungle paths. A hidden gem of Sri Lankan garden design.", entry_fee: "LKR 1500 (foreign adults)", hours: "8:00am – 5:00pm daily" },
  { name: "Lunuganga", category: "Garden", lat: 6.4197, lng: 80.0150, description: "The country estate of legendary Sri Lankan architect Geoffrey Bawa, set on a cinnamon-covered hill above a lagoon near Bentota. Considered one of the finest gardens in Asia with curated vistas, sculptures, and tropical plantings. Now operated as a boutique hotel with garden tours.", entry_fee: "LKR 2000 (garden tour)", hours: "9:00am – 5:00pm daily" },
  { name: "Jungle Beach", category: "Beach", lat: 6.0375, lng: 80.2750, description: "A secluded cove hidden behind a forested headland near Unawatuna, accessible by a short forest trail or boat. Crystal-clear calm water sheltered by rocks, ideal for snorkelling. One of the most beautiful and least-crowded beaches on the south coast.", entry_fee: "Free", hours: "Open 24 hours" },
  { name: "Rekawa Turtle Beach", category: "Wildlife", lat: 6.0492, lng: 80.8550, description: "One of Asia's most important nesting beaches for sea turtles, where five species including the rare leatherback come ashore nightly. Evening guided walks with conservation volunteers to watch nesting females and hatchling releases in their natural habitat.", entry_fee: "LKR 400 (conservation donation)", hours: "Night visits from 8:00pm daily" },
];

async function seed() {
  console.log(`Seeding ${locations.length} locations…`);

  // Insert in batches of 50
  const batchSize = 50;
  let inserted = 0;

  for (let i = 0; i < locations.length; i += batchSize) {
    const batch = locations.slice(i, i + batchSize);
    const { error } = await supabase.from("locations").insert(batch);
    if (error) {
      console.error(`Batch ${i / batchSize + 1} failed:`, error.message);
      process.exit(1);
    }
    inserted += batch.length;
    console.log(`  Inserted ${inserted} / ${locations.length}`);
  }

  console.log("✓ Seed complete");
  process.exit(0);
}

seed();
